In [15]:
import torch
import numpy as np

### Initializing a tensor

### 초기화 방법 1 : 지정된 값으로 Tensor 초기화

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
x_data.shape

torch.Size([2, 2])

### 초기화 방법 2: 랜덤한 값으로 Tensor 초기화

In [10]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


In [11]:
rand_tensor

tensor([[0.3978, 0.6849, 0.4300],
        [0.5301, 0.7346, 0.9368]])

In [12]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### 초기화 방법 3: numpy 배열로부터 Tensor 초기화

In [16]:
data = [[1,2],[3,4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [17]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [18]:
x_np.shape

torch.Size([2, 2])

In [19]:
x_np.dtype

torch.int32

### Tensor 데이터의 형식 지정

### torch.float32 형식으로 초기화

In [20]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data, dtype = torch.float32)

In [21]:
x_data

tensor([[1., 2.],
        [3., 4.]])

In [23]:
x_data.dtype

torch.float32

### torch.uint8 형식으로 초기화

In [26]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data, dtype = torch.uint8)

In [27]:
x_data

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [28]:
x_data = x_data.to(torch.float16)

In [29]:
x_data.dtype

torch.float16

### 다른 DEVICE로 Tensor 옮기기

In [30]:
torch.cuda.is_available()

False

In [32]:
tensor = x_data.to("cuda")

AssertionError: Torch not compiled with CUDA enabled

In [34]:
x_data.cpu()
x_data.to('cpu')

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float16)

In [35]:
x_data.device

device(type='cpu')

### Tensor을 활용한 연산

### Indexing

In [36]:
tensor = torch.ones(4,4)

In [42]:
print(f"First row : {tensor[0]}")
print(f"First columns : {tensor[:, 0]}")
print(f"last columns : {tensor[:, -1]}")
tensor[:,1] = 0
print(tensor)

First row : tensor([1., 1., 1., 1.])
First columns : tensor([1., 1., 1., 1.])
last columns : tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### concatenation

In [45]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)

In [46]:
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

### Arithmetric

In [50]:
y1 = tensor @ tensor.T

In [51]:
y2 = tensor.matmul(tensor.T)

In [52]:
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [53]:
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [56]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

In [57]:
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [58]:
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### Inplace Operation

In [59]:
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [60]:
tensor + 5

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [62]:
tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [63]:
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])