In [1]:
import torch

In [3]:
BATCH_SIZE = 32
FEATURE_SIZE = 128
x = torch.rand(BATCH_SIZE, FEATURE_SIZE)

In [4]:
print(x)

tensor([[0.7371, 0.5046, 0.9561,  ..., 0.1558, 0.9466, 0.9775],
        [0.9328, 0.4737, 0.9762,  ..., 0.3820, 0.6448, 0.5113],
        [0.0172, 0.1320, 0.9455,  ..., 0.6291, 0.7828, 0.0854],
        ...,
        [0.2521, 0.9534, 0.7614,  ..., 0.8870, 0.8253, 0.1639],
        [0.4932, 0.5557, 0.2719,  ..., 0.9236, 0.1464, 0.3834],
        [0.5953, 0.5836, 0.5740,  ..., 0.1319, 0.1815, 0.5666]])


In [6]:
x.shape

torch.Size([32, 128])

In [7]:
in_features = 128
out_features = 64
layer_1 =torch.nn.Linear(in_features= in_features, out_features = out_features, bias = True)

In [8]:
layer_1

Linear(in_features=128, out_features=64, bias=True)

In [10]:
layer_1.weight.shape

torch.Size([64, 128])

In [12]:
layer_1.bias.shape

torch.Size([64])

In [20]:
x = torch.rand(8,128)

In [21]:
output1 = layer_1(x)

In [25]:
output2 = x @ layer_1.weight.T + layer_1.bias

In [26]:
output1

tensor([[ 1.1020e-01,  2.9509e-01,  4.8164e-01, -2.2658e-01, -4.9449e-02,
         -1.3860e-01, -5.7081e-01,  8.4916e-02,  4.0170e-01,  3.7179e-01,
         -2.4636e-01, -1.1336e-01,  6.6437e-02, -2.4371e-01,  1.0007e-01,
          1.1593e-01, -7.6332e-02, -4.4866e-01,  2.2518e-01, -1.1240e-01,
          6.6959e-01, -6.0387e-01, -5.8125e-01,  2.3008e-01, -3.7608e-01,
         -1.2007e-01,  3.0914e-01,  7.4999e-02,  3.6805e-01, -4.3019e-01,
         -1.7514e-01,  8.3995e-02,  1.5813e-01,  1.1670e-01,  1.3173e-02,
         -2.9873e-01, -1.0980e-01, -3.9789e-01,  1.4715e-01, -1.4649e-01,
          3.0214e-01,  1.5818e-02, -2.3811e-01, -7.7500e-02, -1.1024e-01,
          3.7595e-01, -3.9336e-02, -1.7900e-02,  6.5723e-01, -6.1482e-01,
          2.7551e-02, -1.6511e-01,  2.3932e-02,  5.2502e-01, -2.0807e-01,
         -3.0404e-02,  7.0816e-01, -6.7593e-01,  8.6542e-02, -4.8532e-02,
         -4.0545e-01,  5.3413e-02, -5.8288e-02,  1.1081e-01],
        [-1.3515e-01, -1.3453e-01,  3.2858e-01, -3

In [27]:
output2

tensor([[ 1.1020e-01,  2.9509e-01,  4.8164e-01, -2.2658e-01, -4.9449e-02,
         -1.3860e-01, -5.7081e-01,  8.4916e-02,  4.0170e-01,  3.7179e-01,
         -2.4636e-01, -1.1336e-01,  6.6437e-02, -2.4371e-01,  1.0007e-01,
          1.1593e-01, -7.6332e-02, -4.4866e-01,  2.2518e-01, -1.1240e-01,
          6.6959e-01, -6.0387e-01, -5.8125e-01,  2.3008e-01, -3.7608e-01,
         -1.2007e-01,  3.0914e-01,  7.4999e-02,  3.6805e-01, -4.3019e-01,
         -1.7514e-01,  8.3995e-02,  1.5813e-01,  1.1670e-01,  1.3173e-02,
         -2.9873e-01, -1.0980e-01, -3.9789e-01,  1.4715e-01, -1.4649e-01,
          3.0214e-01,  1.5818e-02, -2.3811e-01, -7.7500e-02, -1.1024e-01,
          3.7595e-01, -3.9336e-02, -1.7900e-02,  6.5723e-01, -6.1482e-01,
          2.7551e-02, -1.6511e-01,  2.3932e-02,  5.2502e-01, -2.0807e-01,
         -3.0404e-02,  7.0816e-01, -6.7593e-01,  8.6542e-02, -4.8532e-02,
         -4.0545e-01,  5.3413e-02, -5.8288e-02,  1.1081e-01],
        [-1.3515e-01, -1.3453e-01,  3.2858e-01, -3

In [28]:
import torch.nn as nn

In [29]:
sigmoid = nn.Sigmoid()

In [30]:
tanh = nn.Tanh()

In [31]:
relu = nn.ReLU()

In [32]:
softmax = nn.Softmax()

### Fully Connected Neural Network

In [37]:
in_features = 128
out_features = 64

layer_1 = nn.Linear(in_features = in_features, out_features = out_features, bias = True)
act_fn1 = nn.Tanh()

In [38]:
layer_2 = nn.Linear(in_features = 64, out_features = 16, bias = True)
act_fn2 = nn.Tanh()

In [39]:
layer_3 = nn.Linear(in_features = 16, out_features = 1, bias = True)
act_fn3 = nn.Sigmoid()

In [41]:
out_1 = act_fn1(layer_1(x))

In [45]:
out_1.shape

torch.Size([8, 64])

In [42]:
out_2 = act_fn2(layer_2(out_1))

In [43]:
out_3 = act_fn3(layer_3(out_2))

In [46]:
out_3.shape

torch.Size([8, 1])

## nn.Sequential

In [49]:
model= nn.Sequential(
    nn.Linear(in_features = 128, out_features = 64, bias = True),
    nn.Tanh(),
    nn.Linear(in_features = 64, out_features = 16, bias = True),
    nn.Tanh(),
    nn.Linear(in_features = 16, out_features = 1, bias = True),
    nn.Sigmoid()
)

In [53]:
x = torch.rand(8,128)
model(x).shape

torch.Size([8, 1])

In [54]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.layer= nn.Sequential(
            nn.Linear(in_features = 128, out_features = 64, bias = True),
            nn.Tanh(),
            nn.Linear(in_features = 64, out_features = 16, bias = True),
            nn.Tanh(),
            nn.Linear(in_features = 16, out_features = 1, bias = True),
            nn.Sigmoid()
        )
    def forward(self, x):
        return self.layer(x)

In [55]:
model = NeuralNetwork()
model(x)

tensor([[0.4437],
        [0.4441],
        [0.4592],
        [0.4376],
        [0.4360],
        [0.4321],
        [0.4307],
        [0.4522]], grad_fn=<SigmoidBackward0>)