In [1]:
import torch

### 4.1 Pytorch

### scalar


In [10]:
sca1 = torch.tensor([1])
print(scalar1)

sca2 = torch.tensor([3])
print(scalar2)

tensor([1])
tensor([3])


In [11]:
add_scalar = sca1 + sca2
print(add_scalar)

tensor([4])


In [12]:
sub_scalar = sca1 - sca2
print(sub_scalar)

tensor([-2])


In [13]:
mul_scalar = sca1 * sca2
print(mul_scalar)

tensor([3])


In [14]:
div_scalar = sca1 / sca2
print(div_scalar)

tensor([0.3333])


In [15]:
torch.add(scalar1, scalar2)

tensor([4])

In [16]:
torch.sub(scalar1, scalar2)

tensor([-2])

In [17]:
torch.mul(scalar1, scalar2)

tensor([3])

In [19]:
torch.div(scalar1, scalar2)

tensor([0.3333])

### vector

In [20]:
vec1 = torch.tensor([1,2,3])
print(vec1)

vec2 = torch.tensor([4,5,6])
print(vec2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [21]:
add_vector = vec1 + vec2
print(add_vector)

tensor([5, 7, 9])


In [22]:
sub_vector = vec1 - vec2
print(sub_vector)

tensor([-3, -3, -3])


In [23]:
mul_vector = vec1 * vec2
print(mul_vector)

tensor([ 4, 10, 18])


In [25]:
div_vector = vec1 / vec2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


In [26]:
torch.add(vec1 ,vec2)

tensor([5, 7, 9])

In [27]:
torch.sub(vec1, vec2)

tensor([-3, -3, -3])

In [28]:
torch.mul(vec1, vec2)

tensor([ 4, 10, 18])

In [29]:
torch.div(vec1, vec2)

tensor([0.2500, 0.4000, 0.5000])

In [30]:
torch.dot(vec1 , vec2)

tensor(32)

### 행렬

In [32]:
mat1 = torch.tensor([[1,2],[3,4]])
print(mat1)

mat2 = torch.tensor([[5,6], [7,8]])
print(mat2)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])


In [33]:
sum_mat = mat1 + mat2
print(sum_mat)

tensor([[ 6,  8],
        [10, 12]])


In [34]:
sub_mat = mat1 - mat2
print(sub_mat)

tensor([[-4, -4],
        [-4, -4]])


In [35]:
mul_mat = mat1 * mat2
print(mul_mat)

tensor([[ 5, 12],
        [21, 32]])


In [36]:
div_mat = mat1 / mat2
print(div_mat)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [37]:
torch.add(mat1, mat2)

tensor([[ 6,  8],
        [10, 12]])

In [38]:
torch.sub(mat1, mat2)

tensor([[-4, -4],
        [-4, -4]])

In [39]:
torch.mul(mat1, mat2)

tensor([[ 5, 12],
        [21, 32]])

In [40]:
torch.div(mat1, mat2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

### 텐서

In [48]:
ten1 = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print(ten1)

ten2 = torch.tensor([[[9,10],[11,12]],[[13,14],[15,16]]])
print(ten2)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]])


In [50]:
print(sca1.size())
print(vec1.size())
print(mat1.size())
print(ten1.size()) # 뒤에 2개 2x2 행렬이 앞에 2개 있다는 것을 의미

torch.Size([1])
torch.Size([3])
torch.Size([2, 2])
torch.Size([2, 2, 2])


In [51]:
sum_ten = ten1 + ten2
print(sum_ten)

tensor([[[10, 12],
         [14, 16]],

        [[18, 20],
         [22, 24]]])


In [52]:
sub_ten = ten1 - ten2
print(sub_ten)

tensor([[[-8, -8],
         [-8, -8]],

        [[-8, -8],
         [-8, -8]]])


In [53]:
mul_ten = ten1 * ten2
print(mul_ten)

tensor([[[  9,  20],
         [ 33,  48]],

        [[ 65,  84],
         [105, 128]]])


In [54]:
div_ten = ten1 / ten2
print(div_ten)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [55]:
torch.add(ten1, ten2)

tensor([[[10, 12],
         [14, 16]],

        [[18, 20],
         [22, 24]]])

In [56]:
torch.sub(ten1, ten2)

tensor([[[-8, -8],
         [-8, -8]],

        [[-8, -8],
         [-8, -8]]])

In [57]:
torch.mul(ten1, ten2)

tensor([[[  9,  20],
         [ 33,  48]],

        [[ 65,  84],
         [105, 128]]])

In [58]:
torch.div(ten1, ten2)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

In [60]:
torch.matmul(ten1, ten2) #행렬 곱

tensor([[[ 31,  34],
         [ 71,  78]],

        [[155, 166],
         [211, 226]]])

In [61]:
torch.matmul(mat1, mat2) #행렬 곱

tensor([[19, 22],
        [43, 50]])

In [62]:
torch.mul(mat1, mat2)

tensor([[ 5, 12],
        [21, 32]])

### 4.2 Autograd

In [63]:
import torch

if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device("cpu")

In [71]:
BATCH_SIZE = 64 #배치가 64라서 
INPUT_SIZE = 1000 #입력층의 노드 개수, 입력 데이터의 크기가 1000이라는 말. (64, 1000) 구조로 데이터가 들어감. 
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10

In [84]:
x = torch.randn(BATCH_SIZE, INPUT_SIZE, device = DEVICE, dtype = torch.float, requires_grad = False)
y = torch.randn(BATCH_SIZE, OUTPUT_SIZE, device = DEVICE, dtype = torch.float, requires_grad = False)
w1 = torch.randn(INPUT_SIZE, HIDDEN_SIZE, device = DEVICE, dtype = torch.float, requires_grad = True)
w2 = torch.randn(HIDDEN_SIZE, OUTPUT_SIZE, device = DEVICE, dtype = torch.float, requires_grad = True)

In [85]:
learning_rate = 1e-6
for t in range(1, 501):
    y_pred = x.mm(w1).clamp(min = 0).mm(w2)
    
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 0:
        print("Iteration : ",t , '\t', f'Loss : {loss.item()}')
        
    loss.backward()
    
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        
        w1.grad.zero_()
        w2.grad.zero_()

Iteration :  100 	 Loss : 583.5382080078125
Iteration :  200 	 Loss : 3.012698173522949
Iteration :  300 	 Loss : 0.025002874433994293
Iteration :  400 	 Loss : 0.00046435382682830095
Iteration :  500 	 Loss : 5.889447493245825e-05


In [76]:
x.size()

torch.Size([64, 1000])